version: '3'

services:
  app:
    build: .
    container_name: rest-api
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/home/django/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: rest-api-db
    tty: true
    environment:
      - POSTGRES_DB=rest_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - rest-api-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: rest-api-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"

volumes:
  rest-api-pgdata:
    external: true
